# File: .github/workflows/deploy-pages.yml

name: “Build and Deploy Jekyll with Mermaid”

on:
  push:
    branches:
      - main   # whenever you push to main, rebuild & deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository
      - name: “Checkout repository”
        uses: actions/checkout@v3

      # 2) Set up Ruby (choose the version you need; GitHub Pages uses 2.7.x by default)
      - name: “Set up Ruby”
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      # 3) Install Bundler, then your Gemfile’s dependencies
      - name: “Install dependencies”
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # 4) Run the actual Jekyll build (which will load jekyll-diagrams and process <mermaid>)
      - name: “Build site with Jekyll”
        run: bundle exec jekyll build --destination public

      # 5) Deploy the built site (`public/`) to GitHub Pages via the actions‑gh‑pages action
      - name: “Deploy to GitHub Pages”
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages    # or "main" if you want to publish from main/docs/
          # If you’d rather publish into main:/docs, you could do:
          # publish_branch: main
          # publish_dir: ./public
          # publish_dir: ./public
